config/routes.rb
GameDB::Application.routes.draw do
  resources :games

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  get "welcome/index"

   root 'games#new'
   match '/signup',  to: 'users#new',            via: 'get'
   match '/signin',  to: 'sessions#new',         via: 'get'
   match '/signout', to: 'sessions#destroy',     via: 'delete'

  

end

app/models/game.rb
class Game < ActiveRecord::Base
	validates :name, presence:true
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence:true, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def search_game
  	gb = GiantBomb::Search.new("77dcb9ebcdb6c045950580d993599a609aaee78e")
  	@result = gb.find_game(" SEARCH RESULT")
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    gb = GiantBomb::Search.new("77dcb9ebcdb6c045950580d993599a609aaee78e")
    @game_json = gb.find_game(@game.name)
    
    @img_url = @game_json[0].image["icon_url"]
    @name = @game_json[0].name
    @rating = @game_json[0].original_game_rating
    @description = @game_json[0].deck
    #genres
      @genre0 = @game_json[0].genres[0].name

    @developers = @game_json[0].developers[0].name
    @publishers = @game_json[0].publishers[0].name
    
    @release_date = @game_json[0].original_release_date
    #Game Pictures
      @picture1 = @game_json[0].images[0]["screen_url"]
      @picture2 = @game_json[0].images[1]["screen_url"]
      @picture3 = @game_json[0].images[2]["screen_url"]
      @picture4 = @game_json[0].images[3]["screen_url"]
    

  end

  # GET /games/new
  def new
    @game = Game.new
    @micropost = current_user.microposts.build if signed_in?
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :picture)
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      render 'games/new'
    end
  end

  def destroy
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = 'You have successfully signed out.'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the GameDB #{@current_user.name}!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters



    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def sign_out
    	self.current_user = nil
    	cookies.delete(:remember_token)
  	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
    	user == current_user
  	end

    def signed_in_user
      unless signed_in?
        store_location
        flash[:warning] = "Please Sign In" 
        redirect_to signin_url 
      end
    end

	def signed_in?
    	!current_user.nil?
  	end

  	def redirect_back_or(default)
    	redirect_to(session[:return_to] || default)
    	session.delete(:return_to)
  	end

  	def store_location
    	session[:return_to] = request.url if request.get?
  	end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/_form.html.erb
<%= form_for(@game, :html => { :class => "form-inline" }) do |f| %>
      <%= render 'shared/search_error_messages' %>
      <%= f.text_field :name, :class => 'form-control', :placeholder => 'search for games '  %>
      <%= f.submit "Find Game", class: "btn btn-primary col-lg-12 col-md-12 col-sm-12 col-xs-12", id: "search-button" %>  
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="container well">
<h1>Recent Searches</h1>




<table>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.name, game %></td>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

</div>

app/views/games/new.html.erb
  <% if signed_in? %>
  <div class="container well">
  <div class="row">
    <div class="jumbotron">
      <h1>Search GameDB <i class="fa fa-fw fa-gamepad"></i></h1>
      <p class="lead">Our vision is to create a free database of video game information. We aim to provide users with up-to-date information on video games for all platforms.</p>
      <p><%= render 'form' %></p>      
    </div>
  </div>
  <div class="row">
    <aside class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>
  </div>
  <% else %>
  
    <div class="container well">
      <div class="jumbotron">
            <h1>Welcome to GameDB <i class="fa fa-fw fa-gamepad"></i></h1>
            <p class="lead">Our vision is to create a free database of video game information. We aim to provide users with up-to-date information on video games for all platforms.</p>
            <p><%= link_to "Sign up today", signup_path, class: "btn btn-lg btn-success" %></p>
            <p><%= render 'form' %></p>      
      </div>

          <div class="row marketing">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
              <h4><i class="fa fa-user fa-2x fa-fw"></i> User Powered</h4>
              <p>GameDB is a resource created by people who play games: you.</p>

              <h4><i class="fa fa-fw fa-2x fa-group"></i> Social</h4>
              <p>Connect with friends and other gamers and see what new games they are playing.</p>

              <h4><i class="fa fa-fw fa-2x fa-book"></i> One Library</h4>
              <p>Keep track of all the games you've played, regardless of platform.</p><br />
            </div>

            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
              <h4><i class="fa fa-fw fa-2x fa-dollar"></i> Free</h4> 
              <p>GameDB will always be a free, open-source, game database.</p>

              <h4><i class="fa fa-fw fa-2x fa-exchange"></i>  Compare </h4> 
              <p>Compare game libraries with friends to find out what games you have both played.</p>

              <h4><i class="fa fa-fw fa-2x fa-bar-chart-o"></i> Currently Trending</h4>
              <p>Find currently trending games based off user activity.</p><br />
            </div>
          </div>
    </div>

<% end %>

app/views/games/show.html.erb
<div class="container well col-lg-8 col-lg-offset-2">


<ul class="media-list">
  <li class="media">
    <a class="pull-left" href="#">
      <%= image_tag(@img_url, :class => "media-object") %>
    </a>
    <div class="media-body">
      <h1 class="media-heading"><%= @name %></h1>
      <p><%= @description %></p>

      <p><strong>Genres: </strong><%= @genre0 %></p>
      <p><strong>Developer: </strong><%= @developers %></p>
      <p><strong>Publisher: </strong><%= @publishers %></p>
    
      <p><strong>Release Date: </strong><%= @release_date %></p>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	    <!-- Carousel
	    ================================================== -->
	    <div id="myCarousel" class="carousel slide" data-ride="carousel">
	      <!-- Indicators -->
	      <ol class="carousel-indicators">
	        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	        <li data-target="#myCarousel" data-slide-to="1"></li>
	        <li data-target="#myCarousel" data-slide-to="2"></li>
	        <li data-target="#myCarousel" data-slide-to="3"></li>
	      </ol>
	      <div class="carousel-inner">
	        <div class="item active">
	          <%= image_tag(@picture1, :class => "img-rounded") %>
	        </div>
	        <div class="item">
	          <%= image_tag(@picture2, :class => "img-rounded") %>
	        </div>
	        <div class="item">
	          <%= image_tag(@picture3, :class => "img-rounded") %>
	        </div>
	        <div class="item">
	          <%= image_tag(@picture4, :class => "img-rounded") %>
	        </div>
	      </div>
	      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="fa fa-2x fa-angle-left "></i></a>
	      <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="fa fa-2x fa-angle-right "></i></a>
	    </div><!-- /.carousel -->
    </div>

    </div>
  </li>
</ul>

</div>

app/views/layouts/_footer.html.erb
    <div id="footer">
      <div class="container">
        <p class="text-muted credit">GameDB | DePaul University | IS-372 </a>.</p>
      </div>
    </div>

app/views/layouts/_navbar.html.erb
<!--NAVBAR -->
<!--Navbar-->
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><i class="fa fa-fw fa-gamepad"></i> GameDB</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    
    <ul class="nav navbar-nav navbar-left">
    <% if signed_in? %>
      <li><%= link_to "Recently Searched", games_path %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">


    <!-- <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search Games">
      </div>
      <button type="submit" class="btn btn-default">Search <i class="fa fa-fw fa-search"></i> </button>
    </form> -->




      <% if signed_in? %>
        <li><%= link_to "Find Users", users_path %></li>
        <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= @current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>


      <% else %>
        <li class="active"><a href="/signin">Login</a></li>
        <li><a href="/signup">Sign Up</a></li>
      <% end %>
    </ul>

  </div><!-- /.navbar-collapse -->
</nav>
<!-- End Navbar -->
<!--END NAVBAR -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameDB</title>
  <link rel="shortcut icon" href="http://i.imgur.com/8tkgUa1.png"/>
  <link rel="apple-touch-icon"
      sizes="144x144"
      href="http://i.imgur.com/8tkgUa1.png">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type='text/javascript' src="http://imsky.github.io/holder/holder.js"></script>
</head>


<body>
  <div id="wrap">
    <%= render 'layouts/navbar' %>
    <div class="container">
  	<% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </div>
</body>
  <%= render 'layouts/footer' %>
</html>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if @object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <p><strong>Uh-Oh!</strong> We need you to take a look at <%= pluralize(@object.errors.count, "problem") %>.</p><br />
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
    </div>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  
  <div class="field">
    <%= f.text_area :content, placeholder: "I'm playing..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_search_error_messages.html.erb
<% if @game.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <p><strong>Uh-Oh!</strong> you must enter the name of a game.</p>
    </div>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "game") %>
</span>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

	      <div class="form-group">
	      	<%= f.label :name, :class => "col-sm-2 control-label" %>
	      	<div class="col-sm-10">
	      		<%= f.text_field :name, :class => "form-control" %>
	      	</div>
	      </div>

	      <div class="form-group">
	      	<%= f.label :email, :class => "col-sm-2 control-label" %>
	      	<div class="col-sm-10">
	      		<%= f.text_field :email, :class => "form-control"  %>
	      	</div>
	      </div>

	      <div class="form-group">
	      	<%= f.label :password, :class => "col-sm-2 control-label" %>
	      	<div class="col-sm-10">
	      		<%= f.password_field :password, :class => "form-control"  %>
	      	</div>
	      </div>

	      <div class="form-group">
	      	<%= f.label :password_confirmation, "Confirmation", :class => "col-sm-2 control-label" %>
	      	<div class="col-sm-10">
	      		<%= f.password_field :password_confirmation, :class => "form-control"  %>
	      	</div>
	      </div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
     <button type="button" class="btn btn-danger pull-right"><%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %></button>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<div class="container well col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">

<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
		<h1>Update Profile</h1>

		<div class="form-group col-sm-offset-2">
			<%= gravatar_for @user %>
	    	<button class="btn btn-large btn-default"><%= link_to "change", "http://gravatar.com/emails", :target => "_blank"%></button>
    	</div>

	    <%= form_for(@user, :html => { :class => "form-horizontal" }) do |f| %>
	    	<%= render 'fields', f: f %>
	    	<div class="form-group">
	      		<div class="col-sm-offset-2 col-sm-10">
	      			<%= f.submit "Save Changes", class: "btn btn-large btn-primary" %> <%= link_to 'Back', :back, :class => "pull-right" %>
	      		</div>
	      	</div>
	    <% end %>
	</div>
</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<div class="container well col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
	<h1>Find Users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="container well col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">

<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
		<h1>Sign up</h1>

	    <%= form_for(@user, :html => { :class => "form-horizontal" }) do |f| %>
	    	<%= render 'shared/error_messages' %>

	      <div class="form-group">
	      	<%= f.label :name, :class => "col-sm-2 control-label" %>
	      	<div class="col-sm-10">
	      		<%= f.text_field :name, :class => "form-control" %>
	      	</div>
	      </div>

	      <div class="form-group">
	      	<%= f.label :email, :class => "col-sm-2 control-label" %>
	      	<div class="col-sm-10">
	      		<%= f.text_field :email, :class => "form-control"  %>
	      	</div>
	      </div>

	      <div class="form-group">
	      	<%= f.label :password, :class => "col-sm-2 control-label" %>
	      	<div class="col-sm-10">
	      		<%= f.password_field :password, :class => "form-control"  %>
	      	</div>
	      </div>

	      <div class="form-group">
	      	<%= f.label :password_confirmation, "Confirmation", :class => "col-sm-2 control-label" %>
	      	<div class="col-sm-10">
	      		<%= f.password_field :password_confirmation, :class => "form-control"  %>
	      	</div>
	      </div>

	      <div class="form-group">
	      	<div class="col-sm-offset-2 col-sm-10">
	      		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
	      	</div>
	      </div>

	    <% end %>
	</div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container well col-lg-12">

    <div class="row col-lg-4 col-md-4 col-sm-4 col-xs-12"> <!-- Sidebar -->
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
        <h2><small><%= @user.email %></small></h2>
        <p class="pull-left"><%= link_to "Edit", edit_user_path %></p>
    </div>

  <div class="row col-lg-8 col-md-8 col-sm-8 col-xs-12"> <!-- Main Content -->
    <% if @user.microposts.any? %>
      <h3>Games Played (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>

</div>

app/views/welcome/index.html.erb
  <% if signed_in? %>
  <div class="row">
    <aside class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>
  <% else %>
    <div class="container well">
      <div class="jumbotron">
            <h1>Welcome to GameDB <i class="fa fa-fw fa-gamepad"></i></h1>
            <p class="lead">Our vision is to create a free database of video game information. We aim to provide users with up-to-date information on video games for all platforms.</p>
            <p><%= link_to "Sign up today", signup_path, class: "btn btn-lg btn-success" %></p>
          </div>

          <div class="row marketing">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
              <h4><i class="fa fa-user fa-2x fa-fw"></i> User Powered</h4>
              <p>GameDB is a resource created by people who play games: you.</p>

              <h4><i class="fa fa-fw fa-2x fa-group"></i> Social</h4>
              <p>Connect with friends and other gamers and see what new games they are playing.</p>

              <h4><i class="fa fa-fw fa-2x fa-book"></i> One Library</h4>
              <p>Keep track of all the games you've played, regardless of platform.</p><br />
            </div>

            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
              <h4><i class="fa fa-fw fa-2x fa-dollar"></i> Free</h4> 
              <p>GameDB will always be a free, open-source, game database.</p>

              <h4><i class="fa fa-fw fa-2x fa-exchange"></i>  Compare </h4> 
              <p>Compare game libraries with friends to find out what games you have both played.</p>

              <h4><i class="fa fa-fw fa-2x fa-bar-chart-o"></i> Currently Trending</h4>
              <p>Find currently trending games based off user activity.</p><br />
            </div>
          </div>
    </div>
  <% end %>